#
# Copyright (C) 2016 eKing Technology, Inc. All Rights Reserved.
#
# 所有共的配置都写在这里

spring:
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
    
  aop:
    auto: true
    # CGLIB
    proxy-target-class: true